import type { Config } from "tailwindcss";
export default <Partial<Config>>{
  theme: {
    extend: {
      fontSize: {
        g0: "0.618rem",
        g1: "1rem",
        g2: "1.618rem",
        g3: "2.618rem",
        g4: "4.236rem",
        g5: "6.854rem",
        g6: "11.09rem",
      },
      colors: {
        permadi: {
          DEFAULT: "#ABD1C6",
          50: "#EDF5F3",
          100: "#D7E9E4",
          200: "#C1DDD5",
          300: "#ABD1C6",
          400: "#80AEA5",
          500: "#568C85",
          600: "#2B6964",
          700: "#004643",
          800: "#023230",
          900: "#031E1C",
          950: "#050A09",
        },
        merah: {
          DEFAULT: "#E16162",
          50: "#FFDFDE",
          100: "#F9C6C5",
          200: "#F3ADAC",
          300: "#ED9394",
          400: "#E77A7B",
          500: "#E16162",
          600: "#C45254",
          700: "#A74345",
          800: "#893437",
          900: "#6C2528",
          950: "#4F161A",
        },
        biru: {
          DEFAULT: "#3DA9FC",
          50: "#DBF5FF",
          100: "#BBE6FE",
          200: "#9CD7FE",
          300: "#7CC7FD",
          400: "#5DB8FD",
          500: "#3DA9FC",
          600: "#3194DF",
          700: "#257FC1",
          800: "#186AA4",
          900: "#0C5586",
          950: "#004069",
        },
        kuning: {
          DEFAULT: "#F9BC60",
          50: "#FFF8CF",
          100: "#FEECB9",
          200: "#FDE0A3",
          300: "#FBD48C",
          400: "#FAC876",
          500: "#F9BC60",
          600: "#DBA552",
          700: "#BD8D44",
          800: "#9F7635",
          900: "#815E27",
          950: "#634719",
        },
      },
      fontFamily: {
        body: ["Schibsted Grotesk ", "sans-serif"],
        title: ["Rubik", "sans-serif"],
      },
      typography: ({ theme }: { theme: any }) => ({
        DEFAULT: {
          css: {
            "code::before": { content: "" },
            "code::after": { content: "" },
          },
        },
        permadi: {
          css: {
            "--tw-prose-body": theme("colors.permadi[800]"),
            "--tw-prose-headings": theme("colors.permadi[900]"),
            "--tw-prose-lead": theme("colors.permadi[700]"),
            "--tw-prose-links": theme("colors.permadi[900]"),
            "--tw-prose-bold": theme("colors.permadi[900]"),
            "--tw-prose-counters": theme("colors.permadi[600]"),
            "--tw-prose-bullets": theme("colors.permadi[400]"),
            "--tw-prose-hr": theme("colors.permadi[300]"),
            "--tw-prose-quotes": theme("colors.permadi[900]"),
            "--tw-prose-quote-borders": theme("colors.permadi[300]"),
            "--tw-prose-captions": theme("colors.permadi[700]"),
            "--tw-prose-code": theme("colors.permadi[900]"),
            "--tw-prose-pre-code": theme("colors.permadi[100]"),
            "--tw-prose-pre-bg": theme("colors.permadi[500]"),
            "--tw-prose-th-borders": theme("colors.permadi[300]"),
            "--tw-prose-td-borders": theme("colors.permadi[200]"),
            "--tw-prose-invert-body": theme("colors.permadi[200]"),
            "--tw-prose-invert-headings": theme("colors.kuning"),
            "--tw-prose-invert-lead": theme("colors.permadi[300]"),
            "--tw-prose-invert-links": theme("colors.kuning"),
            "--tw-prose-invert-bold": theme("colors.kuning"),
            "--tw-prose-invert-counters": theme("colors.permadi[400]"),
            "--tw-prose-invert-bullets": theme("colors.permadi[600]"),
            "--tw-prose-invert-hr": theme("colors.permadi[700]"),
            "--tw-prose-invert-quotes": theme("colors.permadi[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.permadi[700]"),
            "--tw-prose-invert-captions": theme("colors.permadi[400]"),
            "--tw-prose-invert-code": theme("colors.kuning"),
            "--tw-prose-invert-pre-code": theme("colors.permadi[300]"),
            "--tw-prose-invert-pre-bg": "rgb(86 140 133 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.permadi[600]"),
            "--tw-prose-invert-td-borders": theme("colors.permadi[700]"),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
    "./storyblok/**/*.{vue,js}",
    "./content/**/*.md",
  ],
};
